# Function to set colors based on theme
function set_rose_pine_colors
  switch $argv[1]
    case "base"
      set -gx C_BASE "#191724"
      set -gx C_SURFACE "#1f1d2e"
      set -gx C_OVERLAY "#26233a"
      set -gx C_MUTED "#6e6a86"
      set -gx C_SUBTLE "#908caa"
      set -gx C_TEXT "#e0def4"
      set -gx C_LOVE "#eb6f92"
      set -gx C_GOLD "#f6c177"
      set -gx C_ROSE "#ebbcba"
      set -gx C_PINE "#31748f"
      set -gx C_FOAM "#9ccfd8"
      set -gx C_IRIS "#c4a7e7"
      set -gx C_HIGHLIGHT_LOW "#21202e"
      set -gx C_HIGHLIGHT_MED "#403d52"
      set -gx C_HIGHLIGHT_HIGH "#524f67"
    case "moon"
      set -gx C_BASE "#191724"
      set -gx C_SURFACE "#1f1d2e"
      set -gx C_OVERLAY "#26233a"
      set -gx C_MUTED "#6e6a86"
      set -gx C_SUBTLE "#908caa"
      set -gx C_TEXT "#e0def4"
      set -gx C_LOVE "#eb6f92"
      set -gx C_GOLD "#f6c177"
      set -gx C_ROSE "#ebbcba"
      set -gx C_PINE "#31748f"
      set -gx C_FOAM "#9ccfd8"
      set -gx C_IRIS "#c4a7e7"
      set -gx C_HIGHLIGHT_LOW "#21202e"
      set -gx C_HIGHLIGHT_MED "#403d52"
      set -gx C_HIGHLIGHT_HIGH "#524f67"
    case "dawn"
      set -gx C_BASE "#faf4ed"
      set -gx C_SURFACE "#fffaf3"
      set -gx C_OVERLAY "#f2e9e1"
      set -gx C_MUTED "#9893a5"
      set -gx C_SUBTLE "#797593"
      set -gx C_TEXT "#575279"
      set -gx C_LOVE "#b4637a"
      set -gx C_GOLD "#ea9d34"
      set -gx C_ROSE "#d7827e"
      set -gx C_PINE "#286983"
      set -gx C_FOAM "#56949f"
      set -gx C_IRIS "#907aa9"
      set -gx C_HIGHLIGHT_LOW "#f4ede8"
      set -gx C_HIGHLIGHT_MED "#dfdad9"
      set -gx C_HIGHLIGHT_HIGH "#cecacd"
    case '*'
      echo "Theme '$C_ROSE_PINE_THEME' not recognized. Available options: moon, dawn, base"
      return 1
  end
end

# Call the function to set colors
set_rose_pine_colors "moon"
